### ISSUE TITLE
Can’t enter verification code on Arch KDE

### ISSUE THREAD

**Issue by gorhatlin** [vyvir/althea#27] opened 2024-08-05 19:30 UTC
After inputing username and password, I get verification code on my iPad, but I can’t enter it in Verification window. It is too small, I resize it, but there are noinput fields. Same happens on Wayland and Xorg KDE session. Any help?

**Comment by vyvir** [comment] 2024-08-06 18:33
Could you provide a screenshot?

**Comment by vyvir** [comment] 2024-08-06 18:33
And show output in console

**Comment by gorhatlin** [comment] 2024-08-07 17:30
From Xorg session of KDE, I get to the point where I get verification code on my iPad and need to enter it in verification window. It is very small:
![1](https://github.com/user-attachments/assets/908828f8-208c-44ca-9325-57f7b3175fef)
and when I resize it, it is empty:
![2](https://github.com/user-attachments/assets/62bf329f-d1cd-4a80-972e-e887a0e20e6a)
Terminal output in Konsole is shown in images.

**Comment by fish4terrisa-MSDSM** [comment] 2024-08-08 02:59
Hmmmm.... That seems to be a bug of qt/KDE. AltLinux works perfectly in Arch/mate.

**Comment by gorhatlin** [comment] 2024-08-08 07:53
I installed whole Mate desktop on top of my KDE setup and same problem occurs:
![1](https://github.com/user-attachments/assets/38791a89-edbe-40d2-a790-c5de6f5036a7)
I think I miss some package in my installation for AltLinux to work properly. But which one?

**Comment by cucumber-sp** [comment] 2024-08-08 18:00
Same here

**Comment by cucumber-sp** [comment] 2024-08-08 18:01
Gnome. Arch linux

**Comment by cucumber-sp** [comment] 2024-08-08 18:05
Managed to make it work. I saved login and password, after reload i've entered verification code and it crashed, for the third time it worked well with saved data

**Comment by gorhatlin** [comment] 2024-08-08 18:17
It works, thanx [cucumber-sp](https://github.com/cucumber-sp)

**Comment by WerIstLuka** [comment] 2024-08-31 09:47
same problem on linux mint 21.3 cinnamon 6.0.4

**Comment by vyvir** [comment] 2024-09-22 13:28
Hi, try the latest version to see if the issue persists

**Comment by FrenchToucan** [comment] 2024-09-26 14:13
> Managed to make it work. I saved login and password, after reload i've entered verification code and it crashed, for the third time it worked well with saved data

Whenever I try to use saved credentials, I get the following error in the terminal:
DNSServiceRegister result: -65537
Traceback (most recent call last):
  File "/home/mike/Downloads/althea-main/main.py", line 181, in altstoreinstall
    win1()
  File "/home/mike/Downloads/althea-main/main.py", line 278, in win1
    winerm()
  File "/home/mike/Downloads/althea-main/main.py", line 264, in winerm
    apple_id, password = line.split("ł") # unacceptable char both in e-mail and apple id

**Comment by vyvir** [comment] 2024-09-27 13:21
> > Managed to make it work. I saved login and password, after reload i've entered verification code and it crashed, for the third time it worked well with saved data
> 
> Whenever I try to use saved credentials, I get the following error in the terminal: DNSServiceRegister result: -65537 Traceback (most recent call last): File "/home/mike/Downloads/althea-main/main.py", line 181, in altstoreinstall win1() File "/home/mike/Downloads/althea-main/main.py", line 278, in win1 winerm() File "/home/mike/Downloads/althea-main/main.py", line 264, in winerm apple_id, password = line.split("ł") # unacceptable char both in e-mail and apple id ^^^^^^^^^^^^^^^^^^ ValueError: not enough values to unpack (expected 2, got 1)

Should be fixed now

**Comment by Gingeh** [comment] 2024-12-08 01:35
This is caused by #44

**Closed** 2024-12-08 10:51 UTC
Labels: bug
