### ISSUE TITLE
Can't refresh app on altstore

### ISSUE THREAD

**Issue by azeALI** [vyvir/althea#31] opened 2024-08-26 15:23 UTC
Error Description
Incorrect Content-Type: must be textual to extract_string, JSON to extract_json.

Failure Reason
Incorrect Content-Type: must be textual to extract_string, JSON to extract_json.

Title
Failed to Refresh AltStore

//Thist error message occurs inside altstore app when trying to refresh an app

**Comment by vyvir** [comment] 2024-08-30 13:36
Duplicate of #29

**Closed by vyvir** 2024-08-30 13:36 UTC
